import "server-only";
import { createHmac, timingSafeEqual } from "node:crypto";

function getSecret(): string {
  // Reuses the app's existing auth secret (with a distinct HMAC purpose
  // string mixed in) rather than requiring a brand-new environment
  // variable just for this one feature.
  return `debtor-pay-link:${process.env.BETTER_AUTH_SECRET ?? "dev-only-insecure-secret"}`;
}

/**
 * A debtor's SMS/WhatsApp reminder needs a link they can tap without
 * signing in — this proves the link was actually generated by this app
 * for this specific sale, not just a guessed cuid (Sale ids aren't
 * meaningfully guessable either, but this is cheap defense-in-depth for a
 * link that lets someone pay money into a specific sale).
 */
export function createPaymentLinkToken(saleId: string): string {
  const signature = createHmac("sha256", getSecret()).update(saleId).digest("base64url");
  return Buffer.from(`${saleId}.${signature}`, "utf8").toString("base64url");
}

export function verifyPaymentLinkToken(token: string): string | null {
  let decoded: string;
  try {
    decoded = Buffer.from(token, "base64url").toString("utf8");
  } catch {
    return null;
  }

  const separatorIndex = decoded.lastIndexOf(".");
  if (separatorIndex === -1) return null;
  const saleId = decoded.slice(0, separatorIndex);
  const signature = decoded.slice(separatorIndex + 1);
  if (!saleId || !signature) return null;

  const expected = createHmac("sha256", getSecret()).update(saleId).digest("base64url");
  const actual = Buffer.from(signature);
  const expectedBuf = Buffer.from(expected);
  if (actual.length !== expectedBuf.length || !timingSafeEqual(actual, expectedBuf)) return null;

  return saleId;
}
